/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mainproject;

public class App {
    public String getGreeting() {
        return "Hello World!0";
    }

    public String getGreeting2() {
        return "Hello World!0";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
